substitutions:
  devicename: heat-transfer
  friendly_name: Heat Transfer Controller

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  comment: ESPHome replacement for ESPEasy HVAC controller
  project:
    name: jason.heat-transfer
    version: "0.1.0"

esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "BQZlkgUv1KDL3i9HBdH65QS7HvV5Myt/qRH0pdnJn1Q="

ota:
  - platform: esphome
    password: "def80ea13159b5250779bc4902541f89"


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  min_auth_mode: WPA2

  manual_ip:
    static_ip: 192.168.80.123
    gateway: 192.168.80.2
    subnet: 255.255.255.0
    dns1: 192.168.80.2
    dns2: 8.8.8.8

captive_portal:

time:
  - platform: homeassistant
    id: ha_time

packages:
  hardware: !include heat_transfer/hardware.yaml
  sensors: !include heat_transfer/sensors.yaml 
  sensors: !include heat_transfer/outputs.yaml 
